# This is a basic workflow to help you get started with Actions

name: CI to Docker Hub

# Controls when the action will run. Triggers the workflow on push or pull request events
on:
  push:
    branches: [master, dev]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Make Cache Directory
        run: mkdir bootstrap/cache
      
      - name: Set up Node
        uses: actions/setup-node@v1
          
      - name: Build Docker Image
        run: docker-compose build --no-cache
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push to Docker Hub (Master)
        if: contains(github.ref, 'master')
        run: |
          docker tag vatusa/api vatusa/api:${{ steps.vars.outputs.sha_short }}
          docker push vatusa/api:${{ steps.vars.outputs.sha_short }}
          
      - name: Push to Docker Hub (Dev)
        if: contains(github.ref, 'dev')
        run: |
          docker tag vatusa/api vatusa/api:dev
          docker push vatusa/api:dev

      - name: Deploy to Kubernetes Cluster
        if: contains(github.ref, 'master')
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: set image deployment/api *=vatusa/api:${{ steps.vars.outputs.sha_short }} -n web
